version: '3'
services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: lavajato
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
    volumes:
      - .docker/postgres_data:/bitnami/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres_data:
