services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: nodejs
    container_name: app
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M

  app-01:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: nodejs
    container_name: app-01
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 100M

  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile.prod
    image: nginx:alpine
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/data:/var/log/nginx/
    ports:
      - "${STDOUT_PORT_API}:80"
    depends_on:
      - app

  redis-ws:
    container_name: redis-ws
    image: redis:latest
    volumes:
      - .docker/redis/data:/usr/local/etc/redis
    ports:
      - 6379
