services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: backend
    entrypoint: wait-for rabbitmq:5672 -t 15 -- npm run dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules

  db:
    image: bitnami/postgresql:latest
    container_name: db
    restart: always
    tty: true
    environment:
      - POSTGRESQL_DATABASE=${DB_DATABASE}
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - .docker/postgres_data:/bitnami/postgresql/data:rw
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "88:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - .docker/pgadmin_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .docker/rabbitmq/data:/var/lib/rabbitmq
      - .docker/rabbitmq/log:/var/log/rabbitmq
